import type { ScenarioPreset } from '../core/physics/types'

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: 'deep-field',
    label: 'Deep field',
    description: 'Nearly Newtonian intuition. Relativistic lensing and clock-rate differences remain visible but no longer dominate.',
    mode: 'scenario',
    observer: {
      radiusRs: 14,
      radialVelocity: 0,
      tangentialVelocity: 0.12,
      phase: 0.3,
      yaw: 0.15,
      pitch: -0.05,
      fov: 70,
    },
    simulationSpeed: 22000,
  },
  {
    id: 'safe-orbit',
    label: 'Safe orbit',
    description: 'A stable educational orbit outside the ISCO with visible but not extreme time dilation.',
    mode: 'scenario',
    observer: {
      radiusRs: 5.4,
      radialVelocity: 0,
      tangentialVelocity: 0.34,
      phase: 0.9,
      yaw: 0,
      pitch: -0.08,
      fov: 76,
    },
    orbitalMode: 'circular-lock',
    simulationSpeed: 18000,
  },
  {
    id: 'photon-sphere',
    label: 'Photon sphere approach',
    description: 'Strong lensing with rapidly increasing gravitational contribution. Small parameter changes now have large visual impact.',
    mode: 'study',
    observer: {
      radiusRs: 1.9,
      radialVelocity: -0.06,
      tangentialVelocity: 0.48,
      phase: 1.2,
      yaw: 0.08,
      pitch: -0.12,
      fov: 82,
    },
    simulationSpeed: 9000,
    educationalApproximation: true,
  },
  {
    id: 'fast-orbit',
    label: 'Fast fly-by',
    description: 'High tangential velocity makes the Doppler contribution comparable to the gravitational shift.',
    mode: 'study',
    observer: {
      radiusRs: 3.2,
      radialVelocity: 0,
      tangentialVelocity: 0.62,
      phase: -0.4,
      yaw: 0.2,
      pitch: -0.1,
      fov: 78,
    },
    simulationSpeed: 14000,
  },
  {
    id: 'horizon-fall',
    label: 'Horizon infall',
    description: 'Radial infall emphasizes the divergence between proper time and distant observer time.',
    mode: 'study',
    observer: {
      radiusRs: 2.4,
      radialVelocity: -0.22,
      tangentialVelocity: 0.08,
      phase: -1.1,
      yaw: 0,
      pitch: -0.18,
      fov: 84,
    },
    simulationSpeed: 10000,
    educationalApproximation: true,
  },
  {
    id: 'compare-flyby',
    label: 'Observer comparison',
    description: 'A side-by-side case: a fast local fly-by versus a nearly static distant observer.',
    mode: 'compare',
    observer: {
      radiusRs: 4.1,
      radialVelocity: -0.08,
      tangentialVelocity: 0.56,
      phase: 0.65,
      yaw: 0.05,
      pitch: -0.06,
      fov: 74,
    },
    simulationSpeed: 15000,
  },
]
